image: wpilib/roborio-cross-ubuntu:2024-22.04

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apt-get update -y && apt-get install -y openjdk-11-jdk  # Install JDK or adjust as needed
    - ./gradlew build
  artifacts:
    paths:
      - build/
    reports:
      junit: '**/TEST-*.xml'

doxygen:
  stage: build
  script:
    - apt-get update -y && apt-get install -y libtinfo5  # Install required dependencies
    - ./gradlew doxygen
    - mv docs/html public
  artifacts:
    paths:
      - public

format:
  stage: build
  script:
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:deadsnakes/ppa
    - add-apt-repository ppa:git-core/ppa
    - apt-get update
    - apt-get install -y python3.8 git
    - pip install wpiformat
    - git checkout -b pr
    - git branch -f main origin/main
    - wpiformat
    - git --no-pager diff --exit-code HEAD

pages:
  stage: deploy
  script:
    - ls -l public
  artifacts:
    paths:
      - public
  only:
    - main
